name: Merge to Main on Success

on:
  workflow_run:
    workflows:
      - "Tests"
    types:
      - completed

jobs:
  merge_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to main
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          script: |
            const pr = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Merge dev to main',
              head: 'dev',  # Replace with the name of your dev branch
              base: 'main'
            });
            core.setOutput('pull_request_number', pr.data.number);
