name: Linting, Testing and Type Checking Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run linting and formatting checks
        run: |
          pip install black pylint
          black .
          pylint . --exit-zero

      - name: Run tests
        run: pytest
        
      - name: Run type checking
        run: mypy . --ignore-missing-imports